# Numpy Lab
element wise computation \
row major 

In [ ]:
import numpy as np
 
a = [1,2,3]
b = np.array([1,2,3])
print(a*5)
print(5*b)

#  1. insert the correct code for creating a numpy array


In [ ]:
a = ... # use np
print(a) # [1 2 3 4 5]

#  2. consider this function:


In [ ]:
def what(n):
  a = np.array([1, 2, 3, 4], ndmin=n)
  print(a.ndim)
  return a

#     what is the difference between what(1), what(2) and what(3)

print(what(1)) # what do these print and why?
print(what(2))
print(what(3))

#  3. insert the correct argument for creating a numpy array with 2 dimensions


In [ ]:
a = np.array([1, 2, 3, 4], ... )
print(a) # should print [[1 2 3 4]]

#  4. insert the correct syntax for checking the number of dimensions of a numpy array


In [ ]:
a = np.array([1, 2, 3, 4])
print( ... ) # should print 1 (must refer to a)

b = np.array([[1, 2], [3, 4]])
print( ... ) # should print 2 (must refer to b)


#  5. insert the correct syntax for printing the first item in the array:


In [ ]:
a = np.array([1, 2, 3, 4])
print( ... ) # should print 1 must use a

#  6. insert the correct syntax for printing the number 50 from the array


In [ ]:
a = np.array([10, 20, 30, 40, 50])
print( ... ) # should print 50 must use a

#  7. insert the correct syntax for printing the number 50 from the array


In [ ]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print( ... ) # should print 50 must use a
print( ... ) # should print 50 must using a second way 



#  8. use negative indexing to print the last item in the array


In [ ]:
a = np.array([10, 20, 30, 40, 50])
print( ... ) # should print 50 must use a

#  9. slice out everything from the second item to (not including) the fifth item


In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print( ... ) # should print [15 20 25] must use a

# 10.slice out everything from the third item to (not including) the fifth item


In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print( ... ) # should print [20 25] must use a

# 11. slice out every other item from the second item to (not including) the fifth item


In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print( ... ) # should print [15 25] must use a

# 12. slice out every other item from the entire array


In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print( ... ) # should print [10 20 30 40] must use a

# 13. insert correct syntax to print the datatype of an array


In [ ]:
a = np.array([1, 2, 3])
print( ... ) # should print something indicating this is an array of integers

# 14. insert the correct argument to specify that array should be of type STRING



In [ ]:
a = np.array([1, 2, 3, 4], dtype= ... )

print(a.dtype)
print(a[0] + a[1])
a = np.array([5, 1, -1, 3], dtype='S')
b = a.astype('i') # what happens here? 
print(b[0] + b[1] + b[3]) 
print(a[0] + a[1] + a[3])

# 15. insert correct method to change data type to integer


In [ ]:
a = np.array([1.1, 2.1, 3.1])
b = a.astype( ... )
print(b) # should print [1 2 3] now 

# 16. use the correct method to make a copy of the array


In [ ]:
a = np.array([1, 2, 3, 4, 5])
x = ... # must use a to make a copy of it 

#     then predict the effect of the following expressions


x[0] = -5
print(a) # does a see the change? 
b = a
b[0] = -25
print(a) # does a see the change?

# 17. use the correct method to make a view of this array:


In [ ]:
a = np.array([1, 2, 3, 4, 5])
d = ... 

#     then predict the effect of these expressions:

print(a.base)
print(d.base) # why is this different from all the others?
b = a
print(b.base)
c = a.copy()
print(c.base)

# 18.predict (and explain) the outcome of these expressions


In [42]:
a = np.array([1, 2, 3, 4])
print(a.shape)
a.reshape(1, 4)
print(a)
a.reshape(2, 2)
print(a)
a.reshape(4, 1)
print(a)

(4,)
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


# 19. use the correct numpy method to change the shape of an array from 1-D to 2-D:


In [ ]:
a = np.array([1, 2, 3, 4])
...#write code here must use a
print(a) # must print [[1, 2] [3 4]]

#     now predict and explain the output of these expressions 

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(4, 3)
print(b)
b = a.reshape(3, 4)
print(b)


# 20. use correct numpy method to change shape of an array from 2-D to 1-D


In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
b = a.reshape( ... ) # complete this statement to result in the output below
print(b) # must print [ 1  2  3  4  5  6  7  8  9 10 11 12]

# 21. use a correct numpy method to join two arrays into a single array


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
#c = ... # use np, a and b somehow 
#print(c) # must print [1 2 3 4 5 6]


#     then predict and explain the outcome of the following expressions

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=1) # what is the effect of the second parameter? 
print(c) # what gets printed and why? 
c  = np.stack((a, b), axis = 0) # what does stack do differently (if anything)? 
print(c) # what gets printed and why? 

# 22. use correct numpy syntax to find all items with value 4


In [ ]:
a = np.array([1, 2, 3, 4, 5, 4, 4])
where = ... # complete statement, must use np, a and 4
print(where) # must print (array([3, 5, 6]),)

# 23. use the correct numpy method to return a sorted array


In [ ]:
a = np.array([3, 2, 0, 1])
b = ... # complete statement, must use np and a
print(b) # must print [0 1 2 3] 

# 24. solve exercise 3-1 on page 57


In [4]:
# CONTEXT
# Let’s tackle this problem by using the salary data of Alice, Bob, and Tim. It
# seems like Bob has enjoyed the highest salary in the last three years. But is
# he actually bringing home the most money, considering the individual tax
# rates of our three friends? Take a look at Listing 3-4.
import numpy as np


## Data: yearly salary in ($1000) [2017, 2018, 2019]
names = ['alice','bob','tim']

alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]
salaries = np.array([alice, bob, tim])
taxation = np.array([[0.2, 0.25, 0.22],
                    [0.4, 0.5, 0.5],
                    [0.1, 0.2, 0.1]])
## One-liner
tax_adjusted = salaries-salaries*taxation
print(tax_adjusted)

max_income  = np.max(tax_adjusted)

## Result
print(max_income)


#PROBLEM

# Go back to the taxation example in “Basic Two-Dimensional Array Arithmetic”
# on page 42 and pull the name of the person with the highest salary from
# the matrix by using this idea of selective Boolean indexing. Problem recap:
# How do we find the person with maximum after-tax income in a group of
# people, given their yearly salary and tax rates?

b = tax_adjusted == max_income
print(b)
a = np.argwhere(b)

print(a)

[[79.2  75.75 80.34]
 [66.   54.   52.5 ]
 [81.   70.4  76.5 ]]
81.0
[[False False False]
 [False False False]
 [ True False False]]
[[2 0]]


# 25. predict and explain the effect of the following expressions


In [ ]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np.average(a, axis=0)) # review the meaning of the axis parameter
print(np.average(a, axis=1))
print(np.average(a, axis=2))

# 26. predict and explain the effect of the following expressions


In [ ]:
a = np.array([[[ 1,  2,  3], [22,  5,  6], [ 7,  8,  9]],
              [[11, 12, 10], [ 4, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [13, 23, 24], [25, 26, 27]]])

b = np.sort(a, axis=0)
print(b) # what gets printed and why? 
c = np.sort(a, axis=1)
print(c)
d = np.sort(a, axis=2)
print(d)

# midterm 6 coins

In [ ]:
N = 6
M = 100

a= np.array([
    [.5,.5,0,0,0,0],
    [.5,0,.5,0,0,0],
    [.5,0,0,.5,0,0],
    [.5,0,0,0,.5,0],
    [.5,0,0,0,0,.5],
    [0 ,0,0,0,0,1]])

def create_transition_matrix(N):
    pass

result = np.linalg.matrix_power(a,M-1)
print(result[0][N-1])




