In [1]:
from scipy.spatial.distance import cosine
from scipy.spatial.distance import jaccard
from sklearn.metrics import jaccard_score

# Vectors
A = [4, 5, 0, 5, 1, 0, 3, 2]
B = [0, 3, 4, 3, 1, 2, 1, 0]
C = [2, 0, 1, 2, 0, 4, 5, 3]

A = [1, 1, 0, 1, 1, 0, 1, 1]
B = [0, 1, 1, 1, 1, 1, 1, 0]
C = [1, 0, 1, 1, 0, 1, 1, 1]

A = [1,1,0,1,0,0,1,0]
B = [0,1,1,1,0,0,0,0]
C = [0,0,0,0,0,1,1,1]

# A = [.66,1.66,0,1.66,-2.33,0,-.33,-1.33]
# B = [0,.66,1.66,.66,-1.33,-.33,-.33,0]
# C = [-.83,0,-1.83,-.83,0,1.16,2.16,.16]

# Compute cosine distances
distance_AB = cosine(A, B)
distance_AC = cosine(A, C)
distance_BC = cosine(B, C)


jdistance_AB = jaccard(A, B)
jdistance_AC = jaccard(A, C)
jdistance_BC = jaccard(B, C)


jsdistance_AB = jaccard_score(A, B)
jsdistance_AC = jaccard_score(A, C)
jsdistance_BC = jaccard_score(B, C)


distance_AB, distance_AC, distance_BC

# jdistance_AB, jdistance_AC, jdistance_BC

# jsdistance_AB, jsdistance_AC, jsdistance_BC




(0.42264973081037416, 0.7113248654051871, 1.0)

In [2]:
import numpy as np
from numpy.linalg import norm
import math 

# A = [4, 5, 0, 5, 1, 0, 3, 2]
# B = [0, 3, 4, 3, 1, 2, 1, 0]
# C = [2, 0, 1, 2, 0, 4, 5, 3]

# A = [1, 1, 0, 1, 1, 0, 1, 1]
# B = [0, 1, 1, 1, 1, 1, 1, 0]
# C = [1, 0, 1, 1, 0, 1, 1, 1]



# A = np.array(A)
# B = np.array(B)
# C = np.array(C)

A = [4, 5, 0, 5, 1, 0, 3, 2]
B = [0, 3, 4, 3, 1, 2, 1, 0]
C = [2, 0, 1, 2, 0, 4, 5, 3]

A = [2/3,5/3,0,5/3,-7/3,0,-1/3,-4/3]
B = [0,2/3,5/3,2/3,-4/3,-1/3,-4/3,0]
C = [-5/6,0,-11/6,-5/6,0,7/6,13/6,1/6]

# A = [1, 1, 0, 1, 1, 0, 1, 1]
# B = [0, 1, 1, 1, 1, 1, 1, 0]
# C = [1, 0, 1, 1, 0, 1, 1, 1]

# A = [1,1,0,1,0,0,1,0]
# B = [0,1,1,1,0,0,0,0]
# C = [0,0,0,0,0,1,1,1]


A = np.array(A)
B = np.array(B)
C = np.array(C)

print(A)
print(B)
print(C)

num = np.dot(A,B)
dem1 = norm(A)
dem2 = norm(B)
cosineAB = np.dot(A,B)/(norm(A)*norm(B))
cosineAC = np.dot(A,C)/(norm(A)*norm(C))
cosineBC = np.dot(B,C)/(norm(B)*norm(C))


def cosine_distance(vec1, vec2):
    # Calculate the dot product of the vectors
    dot_product = np.dot(vec1, vec2)
    
    # Compute the magnitude (norm) of each vector
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)
    
    # Calculate the cosine similarity
    cosine_similarity = dot_product / (norm_vec1 * norm_vec2)
    
    # Calculate the cosine distance
    cosine_distance = 1 - cosine_similarity
    
    return cosine_distance

# Example usage

distanceAB = cosine_distance(A, B)
distanceAC = cosine_distance(A, C)
distanceBC = cosine_distance(B,C)

print("Cosine Similarity AB:", cosineAB)
print("Cosine Similarity AC:", cosineAC)
print("Cosine Similarity BC:", cosineBC)

print("Cosine Distance AB:", distanceAB)
print("Cosine Distance AC:", distanceAC)
print("Cosine Distance BC:", distanceBC)







[ 0.66666667  1.66666667  0.          1.66666667 -2.33333333  0.
 -0.33333333 -1.33333333]
[ 0.          0.66666667  1.66666667  0.66666667 -1.33333333 -0.33333333
 -1.33333333  0.        ]
[-0.83333333  0.         -1.83333333 -0.83333333  0.          1.16666667
  2.16666667  0.16666667]
Cosine Similarity AB: 0.5843065474681431
Cosine Similarity AC: -0.24037008503093263
Cosine Similarity BC: -0.7728895117403245
Cosine Distance AB: 0.41569345253185686
Cosine Distance AC: 1.2403700850309327
Cosine Distance BC: 1.7728895117403245


In [3]:
import numpy as np

A = [4, 5, 0, 5, 1, 0, 3, 2]
B = [0, 3, 4, 3, 1, 2, 1, 0]
C = [2, 0, 1, 2, 0, 4, 5, 3]

A = [2/3,5/3,0,5/3,-7/3,0,-1/3,-4/3]
B = [0,2/3,5/3,2/3,-4/3,-1/3,-4/3,0]
C = [-5/6,0,-11/6,-5/6,0,7/6,13/6,1/6]

A = np.array(A)
B = np.array(B)
C = np.array(C)

print(A)
print(B)
print(C)


def average_excluding_zeroes(arr):
    """
    Calculate the average of a numpy array, excluding zeroes.
    """
    # Filter out the zeros
    non_zero_elements = arr[arr != 0]

    # Calculate the average, handling the case where the array might be empty after removing zeros
    if non_zero_elements.size > 0:
        avg = np.mean(non_zero_elements)
    else:
        avg = 0  # Default to 0 if all elements are zero or the array is empty

    return avg

# Example array

# Calculate the average excluding zeroes
average_a = average_excluding_zeroes(A)
average_b = average_excluding_zeroes(B)
average_c = average_excluding_zeroes(C)

average_a, average_b, average_c 




[ 0.66666667  1.66666667  0.          1.66666667 -2.33333333  0.
 -0.33333333 -1.33333333]
[ 0.          0.66666667  1.66666667  0.66666667 -1.33333333 -0.33333333
 -1.33333333  0.        ]
[-0.83333333  0.         -1.83333333 -0.83333333  0.          1.16666667
  2.16666667  0.16666667]


(0.0, 3.700743415417188e-17, 2.312964634635743e-17)

In [4]:
import numpy as np


A = [4, 5, 0, 5, 1, 0, 3, 2]
B = [0, 3, 4, 3, 1, 2, 1, 0]
C = [2, 0, 1, 2, 0, 4, 5, 3]



A = np.array(A)
B = np.array(B)
C = np.array(C)

print(C)
print(average_c)

def subtract_from_non_zero(arr, num):
    """
    Subtract a float number from each element of a numpy array, but only if the element is not zero.
    """
    # Ensure num is a float
    num = float(num)

    # Create a mask for non-zero elements
    non_zero_mask = arr != 0

    print(non_zero_mask)
    print(arr[non_zero_mask] - num)
    # Subtract the number from non-zero elements only
    new = np.full(8,0)
    print(new)
    new = arr[non_zero_mask] - num
    

    return new
# Example array


# Subtracting 2 from each non-zero element
# Subtracting 2 from each non-zero element
d= subtract_from_non_zero(C, average_c)
# e= subtract_from_non_zero(B, average_b)
# f= subtract_from_non_zero(C, average_c)
print(d)
# print(e)
# print(f)



[2 0 1 2 0 4 5 3]
2.312964634635743e-17
[ True False  True  True False  True  True  True]
[2. 1. 2. 4. 5. 3.]
[0 0 0 0 0 0 0 0]
[2. 1. 2. 4. 5. 3.]


In [5]:
import numpy as np
from numpy.linalg import norm

A = [4,0,0,5,1,0,0]
B = [5,5,4,0,0,0,0]
C = [0,0,0,2,4,5,0]

A = np.array(A)
B = np.array(B)
C = np.array(C)

cosineAB = np.dot(A,B)/(norm(A)*norm(B))
cosineAC = np.dot(A,C)/(norm(A)*norm(C))

print("Cosine Similarity:", cosineAB)
print("Cosine Similarity:", cosineAC)

Cosine Similarity: 0.3798685881987931
Cosine Similarity: 0.3220305943597653


In [6]:
# problem 1d

A = [1,1,0,1,0,0,1,0]
B = [0,1,1,1,0,0,0,0]
C = [0,0,0,0,0,1,1,1]

distance_AB = cosine(A, B)
distance_AC = cosine(A, C)
distance_BC = cosine(B, C)

distance_AB, distance_AC, distance_BC



(0.42264973081037416, 0.7113248654051871, 1.0)

In [7]:
A = [4,0,0,5,1,0,0]
B = [5,5,4,0,0,0,0]
C = [0,0,0,2,4,5,0]

distance_AB = cosine(A, B)
distance_AC = cosine(A, C)

distance_AB, distance_AC

(0.6201314118012068, 0.6779694056402347)

In [8]:
from itertools import combinations

# Graph G edges
edges_G = [("A", "B"), ("A", "C"), ("B", "C"), ("B", "D"), ("D", "E"), ("D", "F"), ("D", "G"), ("E", "F"), ("F", "G")]

# Calculate degrees of each node in G
degree_dict = {}
for edge in edges_G:
    for node in edge:
        if node in degree_dict:
            degree_dict[node] += 1
        else:
            degree_dict[node] = 1

# Calculate the number of edges in G' using the formula
num_edges_G_prime = sum(len(list(combinations(range(degree), 2))) for degree in degree_dict.values())
num_edges_G_prime


16

In [17]:
import networkx as nx

G = nx.Graph()

nodes = ['a','b','c','d','e','f','g']
edges = [('a','b'),
         ('a','c'),
         ('b','c'),
         ('b','d'),
         ('d','e'),
         ('e','f'),
         ('f','g'),
         ('g','d'),
         ('d','f')]

G.add_nodes_from(nodes)
G.add_edges_from(edges)

G.edges()

betweeness = nx.edge_betweenness_centrality(G, normalized=False)
betweeness



{('a', 'b'): 5.0,
 ('a', 'c'): 1.0,
 ('b', 'c'): 5.0,
 ('b', 'd'): 12.0,
 ('d', 'e'): 4.5,
 ('d', 'g'): 4.5,
 ('d', 'f'): 4.0,
 ('e', 'f'): 1.5,
 ('f', 'g'): 1.5}

In [4]:
import networkx as nx

G = nx.Graph()

nodes = ['a','b','c','d','e','f']
edges = [('a','b'),
         ('b','c'),
         ('c','d'),
         ('d','e'),
         ('e','f'),
         ('b','e'),
         ('c','f')]

G.add_nodes_from(nodes)
G.add_edges_from(edges)

G.edges()

betweeness = nx.edge_betweenness_centrality(G, normalized=False)
betweeness

{('a', 'b'): 5.0,
 ('b', 'c'): 4.333333333333333,
 ('b', 'e'): 4.333333333333333,
 ('c', 'd'): 2.833333333333333,
 ('c', 'f'): 2.833333333333333,
 ('d', 'e'): 2.833333333333333,
 ('e', 'f'): 2.833333333333333}

In [9]:
def fibs_to(n):
    fibs = [0,1]
    for i in range(2, n+1):
        print(list(range(2,n+1)))
        fibs.append(fibs[-1] + fibs[-2])
    return fibs 

fibs_to(4)


def fib(n):
    v1, v2, v3 = 1, 1, 0    # initialise a matrix [[1,1],[1,0]]
    for rec in bin(n)[3:]:  # perform fast exponentiation of the matrix (quickly raise it to the nth power)
        calc = v2*v2
        v1, v2, v3 = v1*v1+calc, (v1+v3)*v2, calc+v3*v3
        if rec=='1':    v1, v2, v3 = v1+v2, v1, v2
    return v2

for i in range(5):
    print(fib(i))

[2, 3, 4]
[2, 3, 4]
[2, 3, 4]
1
1
1
2
3


In [12]:
a_list = [[5, 2], [9, 4], [3, 3], [10,1]]
a_new_list = sorted(a_list, key=lambda x: x[0])
print(f"The new list is {a_new_list}")

The new list is [[3, 3], [5, 2], [9, 4], [10, 1]]


In [20]:
# Redefining the custom function to calculate edge betweenness for the entire graph

def shortest_path_betweenness_corrected(G, start_node):
    # Find all shortest paths from the start node to all other nodes
    shortest_paths = {end: list(nx.all_shortest_paths(G, start_node, end)) 
                      for end in G.nodes if end != start_node}

    # Initialize edge betweenness
    edge_betweenness = {edge: 0 for edge in G.edges}

    # Count the number of shortest paths passing through each edge
    for paths in shortest_paths.values():
        for path in paths:
            for i in range(len(path) - 1):
                # Ensure the edge is in the right direction
                edge = (path[i], path[i + 1]) if (path[i], path[i + 1]) in edge_betweenness else (path[i + 1], path[i])
                edge_betweenness[edge] += 1

    return edge_betweenness

# Function to calculate edge betweenness for the entire graph using the custom function
def edge_betweenness_for_graph_custom(G):
    # Initialize edge betweenness
    total_edge_betweenness = {edge: 0 for edge in G.edges}

    # Calculate betweenness for each node and add it to the total
    for node in G.nodes:
        node_betweenness = shortest_path_betweenness_corrected(G, node)
        for edge, count in node_betweenness.items():
            total_edge_betweenness[edge] += count

    # Since the graph is undirected, each edge is counted twice, so we need to halve the counts
    for edge in total_edge_betweenness:
        total_edge_betweenness[edge] /= 2

    return total_edge_betweenness

# Recreating the graph and calculating edge betweenness using the custom function


total_edge_betweenness_custom = edge_betweenness_for_graph_custom(G)

total_edge_betweenness_custom



{('a', 'b'): 4.0,
 ('a', 'c'): 4.0,
 ('b', 'c'): 8.0,
 ('b', 'h'): 11.0,
 ('c', 'd'): 11.0,
 ('d', 'e'): 8.0,
 ('d', 'f'): 4.0,
 ('e', 'g'): 11.0,
 ('e', 'f'): 4.0,
 ('g', 'h'): 8.0,
 ('g', 'i'): 4.0,
 ('h', 'i'): 4.0}

In [12]:
# shortest_paths = {end: list(nx.all_shortest_paths(G1, 'a', end)) 
#                       for end in G1.nodes if end != 'a'}

# shortest_path
nx.__version__


'3.2.1'